name: Nightly Release

on:
  workflow_dispatch:  # Manual trigger

  schedule:
  - cron: '0 5 * * *' # 5 AM UTC = Midnight EST
  push:
    branches: 
    - sascha-nightly-updates

jobs:
  nightly:
    #if: ${{ github.repository == 'shipwright-io/build' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_HOST: registry.saschaschwarze.de
      IMAGE_NAMESPACE: shipwright-test
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s')"

    - name: Install crane
      run: curl --fail --silent --location https://github.com/google/go-containerregistry/releases/download/v0.6.0/go-containerregistry_Linux_x86_64.tar.gz | tar -xzf - -C /usr/local/bin crane

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Install Ko
      uses: imjasonh/setup-ko@20b7695b536c640edfafdd378d96c760460f29d6

    - name: Generate and upload release YAMLs
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        TAG: "nightly-${{ steps.date.outputs.date }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make release

        mv release.yaml nightly-${{ steps.date.outputs.date }}.yaml
        gh release upload nightly nightly-${{ steps.date.outputs.date }}.yaml

        mv release-debug.yaml nightly-${{ steps.date.outputs.date }}-debug.yaml
        gh release upload nightly nightly-${{ steps.date.outputs.date }}-debug.yaml
    - name: Update latest tag of supporting images
      run: |
        crane copy "${IMAGE_HOST}/${IMAGE_NAMESPACE}/bundle:${{ steps.date.outputs.date }}" "${IMAGE_HOST}/${IMAGE_NAMESPACE}/bundle:latest"
        crane copy "${IMAGE_HOST}/${IMAGE_NAMESPACE}/git:${{ steps.date.outputs.date }}" "${IMAGE_HOST}/${IMAGE_NAMESPACE}/git:latest"
        crane copy "${IMAGE_HOST}/${IMAGE_NAMESPACE}/mutate-image:${{ steps.date.outputs.date }}" "${IMAGE_HOST}/${IMAGE_NAMESPACE}/mutate-image:latest"

    - name: Package sample build strategies
      run: |
        ko resolve samples/buildstrategies > nightly-${{ steps.date.outputs.date }}-strategies.yaml
        gh release upload nightly nightly-${{ steps.date.outputs.date }}-strategies.yaml
